// Complete currency mapping for all 193 UN-recognized countries
export const currencyMap: Record<string, {
  code: string;
  name: string;
  symbol: string;
  locale: string;
}> = {
  "Afghanistan": { code: "AFN", name: "Afghan Afghani", symbol: "؋", locale: "fa-AF" },
  "Albania": { code: "ALL", name: "Albanian Lek", symbol: "L", locale: "sq-AL" },
  "Algeria": { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", locale: "ar-DZ" },
  "Andorra": { code: "EUR", name: "Euro", symbol: "€", locale: "ca-AD" },
  "Angola": { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", locale: "pt-AO" },
  "Antigua and Barbuda": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-AG" },
  "Argentina": { code: "ARS", name: "Argentine Peso", symbol: "$", locale: "es-AR" },
  "Armenia": { code: "AMD", name: "Armenian Dram", symbol: "֏", locale: "hy-AM" },
  "Australia": { code: "AUD", name: "Australian Dollar", symbol: "$", locale: "en-AU" },
  "Austria": { code: "EUR", name: "Euro", symbol: "€", locale: "de-AT" },
  "Azerbaijan": { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", locale: "az-AZ" },
  "Bahamas": { code: "BSD", name: "Bahamian Dollar", symbol: "$", locale: "en-BS" },
  "Bahrain": { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", locale: "ar-BH" },
  "Bangladesh": { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", locale: "bn-BD" },
  "Barbados": { code: "BBD", name: "Barbadian Dollar", symbol: "$", locale: "en-BB" },
  "Belarus": { code: "BYN", name: "Belarusian Ruble", symbol: "Br", locale: "be-BY" },
  "Belgium": { code: "EUR", name: "Euro", symbol: "€", locale: "nl-BE" },
  "Belize": { code: "BZD", name: "Belize Dollar", symbol: "$", locale: "en-BZ" },
  "Benin": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-BJ" },
  "Bhutan": { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", locale: "dz-BT" },
  "Bolivia": { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", locale: "es-BO" },
  "Bosnia and Herzegovina": { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", symbol: "KM", locale: "bs-BA" },
  "Botswana": { code: "BWP", name: "Botswana Pula", symbol: "P", locale: "en-BW" },
  "Brazil": { code: "BRL", name: "Brazilian Real", symbol: "R$", locale: "pt-BR" },
  "Brunei": { code: "BND", name: "Brunei Dollar", symbol: "$", locale: "ms-BN" },
  "Bulgaria": { code: "BGN", name: "Bulgarian Lev", symbol: "лв", locale: "bg-BG" },
  "Burkina Faso": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-BF" },
  "Burundi": { code: "BIF", name: "Burundian Franc", symbol: "Fr", locale: "fr-BI" },
  "Cabo Verde": { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", locale: "pt-CV" },
  "Cambodia": { code: "KHR", name: "Cambodian Riel", symbol: "៛", locale: "km-KH" },
  "Cameroon": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "fr-CM" },
  "Canada": { code: "CAD", name: "Canadian Dollar", symbol: "$", locale: "en-CA" },
  "Central African Republic": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "fr-CF" },
  "Chad": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "fr-TD" },
  "Chile": { code: "CLP", name: "Chilean Peso", symbol: "$", locale: "es-CL" },
  "China": { code: "CNY", name: "Chinese Yuan", symbol: "¥", locale: "zh-CN" },
  "Colombia": { code: "COP", name: "Colombian Peso", symbol: "$", locale: "es-CO" },
  "Comoros": { code: "KMF", name: "Comorian Franc", symbol: "Fr", locale: "ar-KM" },
  "Congo": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "fr-CG" },
  "Costa Rica": { code: "CRC", name: "Costa Rican Colon", symbol: "₡", locale: "es-CR" },
  "Croatia": { code: "EUR", name: "Euro", symbol: "€", locale: "hr-HR" },
  "Cuba": { code: "CUP", name: "Cuban Peso", symbol: "$", locale: "es-CU" },
  "Cyprus": { code: "EUR", name: "Euro", symbol: "€", locale: "el-CY" },
  "Czech Republic": { code: "CZK", name: "Czech Koruna", symbol: "Kč", locale: "cs-CZ" },
  "Denmark": { code: "DKK", name: "Danish Krone", symbol: "kr", locale: "da-DK" },
  "Djibouti": { code: "DJF", name: "Djiboutian Franc", symbol: "Fr", locale: "fr-DJ" },
  "Dominica": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-DM" },
  "Dominican Republic": { code: "DOP", name: "Dominican Peso", symbol: "RD$", locale: "es-DO" },
  "Ecuador": { code: "USD", name: "United States Dollar", symbol: "$", locale: "es-EC" },
  "Egypt": { code: "EGP", name: "Egyptian Pound", symbol: "£", locale: "ar-EG" },
  "El Salvador": { code: "USD", name: "United States Dollar", symbol: "$", locale: "es-SV" },
  "Equatorial Guinea": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "es-GQ" },
  "Eritrea": { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", locale: "ti-ER" },
  "Estonia": { code: "EUR", name: "Euro", symbol: "€", locale: "et-EE" },
  "Eswatini": { code: "SZL", name: "Swazi Lilangeni", symbol: "L", locale: "en-SZ" },
  "Ethiopia": { code: "ETB", name: "Ethiopian Birr", symbol: "Br", locale: "am-ET" },
  "Fiji": { code: "FJD", name: "Fijian Dollar", symbol: "$", locale: "en-FJ" },
  "Finland": { code: "EUR", name: "Euro", symbol: "€", locale: "fi-FI" },
  "France": { code: "EUR", name: "Euro", symbol: "€", locale: "fr-FR" },
  "Gabon": { code: "XAF", name: "Central African CFA franc", symbol: "Fr", locale: "fr-GA" },
  "Gambia": { code: "GMD", name: "Gambian Dalasi", symbol: "D", locale: "en-GM" },
  "Georgia": { code: "GEL", name: "Georgian Lari", symbol: "₾", locale: "ka-GE" },
  "Germany": { code: "EUR", name: "Euro", symbol: "€", locale: "de-DE" },
  "Ghana": { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", locale: "en-GH" },
  "Greece": { code: "EUR", name: "Euro", symbol: "€", locale: "el-GR" },
  "Grenada": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-GD" },
  "Guatemala": { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", locale: "es-GT" },
  "Guinea": { code: "GNF", name: "Guinean Franc", symbol: "Fr", locale: "fr-GN" },
  "Guinea-Bissau": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "pt-GW" },
  "Guyana": { code: "GYD", name: "Guyanese Dollar", symbol: "$", locale: "en-GY" },
  "Haiti": { code: "HTG", name: "Haitian Gourde", symbol: "G", locale: "ht-HT" },
  "Honduras": { code: "HNL", name: "Honduran Lempira", symbol: "L", locale: "es-HN" },
  "Hungary": { code: "HUF", name: "Hungarian Forint", symbol: "Ft", locale: "hu-HU" },
  "Iceland": { code: "ISK", name: "Icelandic Króna", symbol: "kr", locale: "is-IS" },
  "India": { code: "INR", name: "Indian Rupee", symbol: "₹", locale: "en-IN" },
  "Indonesia": { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", locale: "id-ID" },
  "Iran": { code: "IRR", name: "Iranian Rial", symbol: "﷼", locale: "fa-IR" },
  "Iraq": { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", locale: "ar-IQ" },
  "Ireland": { code: "EUR", name: "Euro", symbol: "€", locale: "en-IE" },
  "Israel": { code: "ILS", name: "Israeli New Shekel", symbol: "₪", locale: "he-IL" },
  "Italy": { code: "EUR", name: "Euro", symbol: "€", locale: "it-IT" },
  "Jamaica": { code: "JMD", name: "Jamaican Dollar", symbol: "$", locale: "en-JM" },
  "Japan": { code: "JPY", name: "Japanese Yen", symbol: "¥", locale: "ja-JP" },
  "Jordan": { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", locale: "ar-JO" },
  "Kazakhstan": { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", locale: "kk-KZ" },
  "Kenya": { code: "KES", name: "Kenyan Shilling", symbol: "Sh", locale: "en-KE" },
  "Kiribati": { code: "AUD", name: "Australian Dollar", symbol: "$", locale: "en-KI" },
  "Korea, North": { code: "KPW", name: "North Korean Won", symbol: "₩", locale: "ko-KP" },
  "Korea, South": { code: "KRW", name: "South Korean Won", symbol: "₩", locale: "ko-KR" },
  "Kuwait": { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", locale: "ar-KW" },
  "Kyrgyzstan": { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", locale: "ky-KG" },
  "Laos": { code: "LAK", name: "Laotian Kip", symbol: "₭", locale: "lo-LA" },
  "Latvia": { code: "EUR", name: "Euro", symbol: "€", locale: "lv-LV" },
  "Lebanon": { code: "LBP", name: "Lebanese Pound", symbol: "£", locale: "ar-LB" },
  "Lesotho": { code: "LSL", name: "Lesotho Loti", symbol: "L", locale: "en-LS" },
  "Liberia": { code: "LRD", name: "Liberian Dollar", symbol: "$", locale: "en-LR" },
  "Libya": { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", locale: "ar-LY" },
  "Liechtenstein": { code: "CHF", name: "Swiss Franc", symbol: "Fr", locale: "de-LI" },
  "Lithuania": { code: "EUR", name: "Euro", symbol: "€", locale: "lt-LT" },
  "Luxembourg": { code: "EUR", name: "Euro", symbol: "€", locale: "lb-LU" },
  "Madagascar": { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", locale: "mg-MG" },
  "Malawi": { code: "MWK", name: "Malawian Kwacha", symbol: "MK", locale: "ny-MW" },
  "Malaysia": { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", locale: "ms-MY" },
  "Maldives": { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", locale: "dv-MV" },
  "Mali": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-ML" },
  "Malta": { code: "EUR", name: "Euro", symbol: "€", locale: "mt-MT" },
  "Marshall Islands": { code: "USD", name: "United States Dollar", symbol: "$", locale: "en-MH" },
  "Mauritania": { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", locale: "ar-MR" },
  "Mauritius": { code: "MUR", name: "Mauritian Rupee", symbol: "₨", locale: "en-MU" },
  "Mexico": { code: "MXN", name: "Mexican Peso", symbol: "$", locale: "es-MX" },
  "Micronesia": { code: "USD", name: "United States Dollar", symbol: "$", locale: "en-FM" },
  "Moldova": { code: "MDL", name: "Moldovan Leu", symbol: "L", locale: "ro-MD" },
  "Monaco": { code: "EUR", name: "Euro", symbol: "€", locale: "fr-MC" },
  "Mongolia": { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", locale: "mn-MN" },
  "Montenegro": { code: "EUR", name: "Euro", symbol: "€", locale: "sr-ME" },
  "Morocco": { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", locale: "ar-MA" },
  "Mozambique": { code: "MZN", name: "Mozambican Metical", symbol: "MT", locale: "pt-MZ" },
  "Myanmar": { code: "MMK", name: "Myanmar Kyat", symbol: "K", locale: "my-MM" },
  "Namibia": { code: "NAD", name: "Namibian Dollar", symbol: "$", locale: "en-NA" },
  "Nauru": { code: "AUD", name: "Australian Dollar", symbol: "$", locale: "en-NR" },
  "Nepal": { code: "NPR", name: "Nepalese Rupee", symbol: "₨", locale: "ne-NP" },
  "Netherlands": { code: "EUR", name: "Euro", symbol: "€", locale: "nl-NL" },
  "New Zealand": { code: "NZD", name: "New Zealand Dollar", symbol: "$", locale: "en-NZ" },
  "Nicaragua": { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", locale: "es-NI" },
  "Niger": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-NE" },
  "Nigeria": { code: "NGN", name: "Nigerian Naira", symbol: "₦", locale: "en-NG" },
  "North Macedonia": { code: "MKD", name: "Macedonian Denar", symbol: "ден", locale: "mk-MK" },
  "Norway": { code: "NOK", name: "Norwegian Krone", symbol: "kr", locale: "nb-NO" },
  "Oman": { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", locale: "ar-OM" },
  "Pakistan": { code: "PKR", name: "Pakistani Rupee", symbol: "₨", locale: "ur-PK" },
  "Palau": { code: "USD", name: "United States Dollar", symbol: "$", locale: "en-PW" },
  "Palestine": { code: "ILS", name: "Israeli New Shekel", symbol: "₪", locale: "ar-PS" },
  "Panama": { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", locale: "es-PA" },
  "Papua New Guinea": { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", locale: "en-PG" },
  "Paraguay": { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", locale: "es-PY" },
  "Peru": { code: "PEN", name: "Peruvian Sol", symbol: "S/", locale: "es-PE" },
  "Philippines": { code: "PHP", name: "Philippine Peso", symbol: "₱", locale: "en-PH" },
  "Poland": { code: "PLN", name: "Polish Zloty", symbol: "zł", locale: "pl-PL" },
  "Portugal": { code: "EUR", name: "Euro", symbol: "€", locale: "pt-PT" },
  "Qatar": { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", locale: "ar-QA" },
  "Romania": { code: "RON", name: "Romanian Leu", symbol: "lei", locale: "ro-RO" },
  "Russia": { code: "RUB", name: "Russian Ruble", symbol: "₽", locale: "ru-RU" },
  "Rwanda": { code: "RWF", name: "Rwandan Franc", symbol: "Fr", locale: "rw-RW" },
  "Saint Kitts and Nevis": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-KN" },
  "Saint Lucia": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-LC" },
  "Saint Vincent and the Grenadines": { code: "XCD", name: "East Caribbean Dollar", symbol: "$", locale: "en-VC" },
  "Samoa": { code: "WST", name: "Samoan Tala", symbol: "T", locale: "en-WS" },
  "San Marino": { code: "EUR", name: "Euro", symbol: "€", locale: "it-SM" },
  "Sao Tome and Principe": { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", locale: "pt-ST" },
  "Saudi Arabia": { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", locale: "ar-SA" },
  "Senegal": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-SN" },
  "Serbia": { code: "RSD", name: "Serbian Dinar", symbol: "дин.", locale: "sr-RS" },
  "Seychelles": { code: "SCR", name: "Seychellois Rupee", symbol: "₨", locale: "en-SC" },
  "Sierra Leone": { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", locale: "en-SL" },
  "Singapore": { code: "SGD", name: "Singapore Dollar", symbol: "$", locale: "en-SG" },
  "Slovakia": { code: "EUR", name: "Euro", symbol: "€", locale: "sk-SK" },
  "Slovenia": { code: "EUR", name: "Euro", symbol: "€", locale: "sl-SI" },
  "Solomon Islands": { code: "SBD", name: "Solomon Islands Dollar", symbol: "$", locale: "en-SB" },
  "Somalia": { code: "SOS", name: "Somali Shilling", symbol: "Sh", locale: "so-SO" },
  "South Africa": { code: "ZAR", name: "South African Rand", symbol: "R", locale: "en-ZA" },
  "South Sudan": { code: "SSP", name: "South Sudanese Pound", symbol: "£", locale: "en-SS" },
  "Spain": { code: "EUR", name: "Euro", symbol: "€", locale: "es-ES" },
  "Sri Lanka": { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", locale: "si-LK" },
  "Sudan": { code: "SDG", name: "Sudanese Pound", symbol: "£", locale: "ar-SD" },
  "Suriname": { code: "SRD", name: "Surinamese Dollar", symbol: "$", locale: "nl-SR" },
  "Sweden": { code: "SEK", name: "Swedish Krona", symbol: "kr", locale: "sv-SE" },
  "Switzerland": { code: "CHF", name: "Swiss Franc", symbol: "Fr", locale: "de-CH" },
  "Syria": { code: "SYP", name: "Syrian Pound", symbol: "£", locale: "ar-SY" },
  "Taiwan": { code: "TWD", name: "New Taiwan Dollar", symbol: "$", locale: "zh-TW" },
  "Tajikistan": { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ", locale: "tg-TJ" },
  "Tanzania": { code: "TZS", name: "Tanzanian Shilling", symbol: "Sh", locale: "en-TZ" },
  "Thailand": { code: "THB", name: "Thai Baht", symbol: "฿", locale: "th-TH" },
  "Timor-Leste": { code: "USD", name: "United States Dollar", symbol: "$", locale: "pt-TL" },
  "Togo": { code: "XOF", name: "West African CFA franc", symbol: "Fr", locale: "fr-TG" },
  "Tonga": { code: "TOP", name: "Tongan Paanga", symbol: "T$", locale: "en-TO" },
  "Trinidad and Tobago": { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$", locale: "en-TT" },
  "Tunisia": { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", locale: "ar-TN" },
  "Turkey": { code: "TRY", name: "Turkish Lira", symbol: "₺", locale: "tr-TR" },
  "Turkmenistan": { code: "TMT", name: "Turkmenistani Manat", symbol: "m", locale: "tk-TM" },
  "Tuvalu": { code: "AUD", name: "Australian Dollar", symbol: "$", locale: "en-TV" },
  "Uganda": { code: "UGX", name: "Ugandan Shilling", symbol: "Sh", locale: "en-UG" },
  "Ukraine": { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", locale: "uk-UA" },
  "United Arab Emirates": { code: "AED", name: "UAE Dirham", symbol: "د.إ", locale: "ar-AE" },
  "United Kingdom": { code: "GBP", name: "British Pound", symbol: "£", locale: "en-GB" },
  "United States": { code: "USD", name: "United States Dollar", symbol: "$", locale: "en-US" },
  "Uruguay": { code: "UYU", name: "Uruguayan Peso", symbol: "$", locale: "es-UY" },
  "Uzbekistan": { code: "UZS", name: "Uzbekistani Som", symbol: "сўм", locale: "uz-UZ" },
  "Vanuatu": { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", locale: "en-VU" },
  "Vatican City": { code: "EUR", name: "Euro", symbol: "€", locale: "it-VA" },
  "Venezuela": { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", locale: "es-VE" },
  "Vietnam": { code: "VND", name: "Vietnamese Dong", symbol: "₫", locale: "vi-VN" },
  "Yemen": { code: "YER", name: "Yemeni Rial", symbol: "﷼", locale: "ar-YE" },
  "Zambia": { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", locale: "en-ZM" },
  "Zimbabwe": { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", locale: "en-ZW" },
};

// Utility function to get currency info by country name
export const getCurrencyByCountry = (countryName: string) => {
  return currencyMap[countryName] || { code: "USD", name: "United States Dollar", symbol: "$", locale: "en-US" };
};

// Utility function to format currency based on locale
export const formatCurrencyByLocale = (
  value: number,
  countryName: string,
  options?: Intl.NumberFormatOptions
): string => {
  const currency = getCurrencyByCountry(countryName);
  const formatter = new Intl.NumberFormat(currency.locale, {
    style: "currency",
    currency: currency.code,
    ...options,
  });
  return formatter.format(value);
};

// Utility function to get currency symbol by country
export const getCurrencySymbol = (countryName: string): string => {
  return getCurrencyByCountry(countryName).symbol;
};

// Utility function to get locale by country
export const getLocaleByCountry = (countryName: string): string => {
  return getCurrencyByCountry(countryName).locale;
};
